import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MonitorSmartphone, ShoppingCart } from "lucide-react";
import Link from "next/link";
import { Toaster } from "@/components/ui/sonner";
import { ClerkProvider } from "@clerk/nextjs";
import Auth from "@/components/auth";
import ReactQueryProvider from "@/providers/ReactQuery";
import dynamic from "next/dynamic";
import DropDownCart from "@/components/cart";
import Footer from "@/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, // slot for childrens
  ads, // slot for  ads
}: Readonly<{
  children: React.ReactNode;
  ads: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClerkProvider
        // appearance={{
        //   elements: {
        //     headerTitle: {
        //       fontSize: 20,
        //     },
        //     formButtonPrimary: {
        //       backgroundColor: "blue",
        //       text: "white",
        //     },
        //   },
        // }}
        >
          <ReactQueryProvider>
            <main className="flex flex-col min-h-screen">
              <header className="fixed flex justify-between items-center shadow-xl px-20 h-20 z-40 border-b bg-white/95 backdrop-blur supports-[backdrop-filter]:bg-white/60 w-full ">
                <div className="flex items-center gap-2">
                  <div className="w-8 h-8 bg-gradient-to-br from-blue-600 to-purple-600 rounded-lg flex items-center justify-center">
                    <span className="text-white font-bold text-sm">MD</span>
                  </div>
                  <Link href="/" className="text-xl font-semibold">
                    MiniDigital
                  </Link>
                </div>
                <div className="flex items-center gap-4">
                  <Auth />
                  <DropDownCart />
                </div>
              </header>
              <div className=" mt-21">
                {children}
                <Toaster />
              </div>
              {/* <div className="my-10 mx-auto flex justify-center">{ads}</div> */}
              <Footer />
            </main>
          </ReactQueryProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
